---
# Simple docker-compose file for kylemanna/openvpn
services:
  openvpn:
    cap_add:
      - NET_ADMIN
    # Build your own latest openvpn image
    image: ${OVPN_IMG}:${OVPN_TAG}
    container_name: openvpn
    hostname: openvpn
    ports:
      # Use public ports like 433 or 8080 or something else
      - "${OVPN_RPORT:-1194}:1194/udp"
    restart: always
    networks:
      - openvpn_net
    volumes:
      - openvpn-data:/etc/openvpn
    command:
      - ovpn_run
      - --cipher
      - AES-256-GCM
      - --max-clients
      - "${MAX_CLIENTS}"


# Both pihole and opernvpn service need to be on the same network openvpn_net
# So that the VPN client can access pihole internal address 172.20.0.2
# Otherwise, you need to use external, host IP address for DNS.
networks:
  openvpn_net:
    external: true
volumes:
  openvpn-data:
    external:
      name: ${OVPN_DATA}
