---
# Simple docker-compose file for kylemanna/openvpn
version: '3.7'
services:
  openvpn:
    cap_add:
      - NET_ADMIN
    # Build your own latest openvpn image
    image: ${OPENVPN_IMG}
    container_name: openvpn
    ports:
      # Use public ports like 433 or 8080 or something else
      - "1194:1194/udp"
    restart: always
    volumes:
      - openvpn-data:/etc/openvpn
    command:
      - ovpn_run
      - --cipher
      - AES-256-CBC
      - --max-clients
      - "${MAX_CLIENTS}"

volumes:
  openvpn-data:
    external:
      name: ${OVPN_DATA}
